# Generated by Django 3.1.2 on 2020-10-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('house', models.CharField(max_length=200)),
                ('blood_status', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
            ],
        ),
    ]
